// <auto-generated />
using System;
using LLeague.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LLeague.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LLeague.Api.Domain.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LLeague.Api.Domain.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ready")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TableId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchParticipants");
                });

            modelBuilder.Entity("LLeague.Api.Domain.MissionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClauseIndex")
                        .HasColumnType("integer");

                    b.Property<string>("MissionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScoresheetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueRaw")
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScoresheetId");

                    b.ToTable("MissionValues");
                });

            modelBuilder.Entity("LLeague.Api.Domain.RobotGameTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Scoresheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("MatchParticipantId")
                        .IsUnique();

                    b.ToTable("Scoresheets");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Number", "Region")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("LLeague.Api.Domain.TeamDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Arrived")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ArrivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("TeamId", "DivisionId")
                        .IsUnique();

                    b.ToTable("TeamDivisions");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Division", b =>
                {
                    b.HasOne("LLeague.Api.Domain.Event", "Event")
                        .WithMany("Divisions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Event", b =>
                {
                    b.HasOne("LLeague.Api.Domain.Season", "Season")
                        .WithMany("Events")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Match", b =>
                {
                    b.HasOne("LLeague.Api.Domain.Division", "Division")
                        .WithMany("Matches")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("LLeague.Api.Domain.MatchParticipant", b =>
                {
                    b.HasOne("LLeague.Api.Domain.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LLeague.Api.Domain.RobotGameTable", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LLeague.Api.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Table");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LLeague.Api.Domain.MissionValue", b =>
                {
                    b.HasOne("LLeague.Api.Domain.Scoresheet", "Scoresheet")
                        .WithMany("Missions")
                        .HasForeignKey("ScoresheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scoresheet");
                });

            modelBuilder.Entity("LLeague.Api.Domain.RobotGameTable", b =>
                {
                    b.HasOne("LLeague.Api.Domain.Division", "Division")
                        .WithMany("Tables")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Scoresheet", b =>
                {
                    b.HasOne("LLeague.Api.Domain.MatchParticipant", "MatchParticipant")
                        .WithOne("Scoresheet")
                        .HasForeignKey("LLeague.Api.Domain.Scoresheet", "MatchParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchParticipant");
                });

            modelBuilder.Entity("LLeague.Api.Domain.TeamDivision", b =>
                {
                    b.HasOne("LLeague.Api.Domain.Division", "Division")
                        .WithMany("TeamDivisions")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LLeague.Api.Domain.Team", "Team")
                        .WithMany("TeamDivisions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Division", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Tables");

                    b.Navigation("TeamDivisions");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Event", b =>
                {
                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Match", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("LLeague.Api.Domain.MatchParticipant", b =>
                {
                    b.Navigation("Scoresheet");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Scoresheet", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Season", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("LLeague.Api.Domain.Team", b =>
                {
                    b.Navigation("TeamDivisions");
                });
#pragma warning restore 612, 618
        }
    }
}
